### ISSUE TITLE
folders in .studio-ignore are still created in Studio

### ISSUE THREAD

**Issue by miasa** [osaton/gulp-studio-push#1]
Local dist tree:

```
dist/
  |__templates/
        |__placeholders/
        |      |__img.jpg
        |__article.html
```

.studio-ignore file:

`dist/templates`

gulp task:

```
var studioSettings = {
  studio  : 'xxx',
  proxy   : yyy'',
  folders : [{
    folderId : '54cf2de1a93bea874fdf38ab', 
    localFolder : 'dist',
    includeSubFolders : true // Create and upload child folders too
  }]
};

gulp.task("push", function() {
  return gulp.src("dist")
             .pipe(studioPush(studioSettings));
});
```

`templates` folder and its subfolders are created in Studio, but no files inside `templates` or subfolders are transferred.

Expected result:

No `templates` folder created in Studio.

**Comment by osaton** [comment]
Thank you for an awesome bug report! Moved to https://github.com/osaton/studio-helper/issues/8
